%%{init: {'theme': 'dark', 'themeVariables': {'primaryColor': '#d97757', 'primaryTextColor': '#e8e6dc', 'primaryBorderColor': '#d97757', 'lineColor': '#d97757', 'secondaryColor': '#1e1e1c', 'tertiaryColor': '#141413', 'background': '#141413', 'mainBkg': '#1e1e1c', 'nodeBorder': '#d97757', 'titleColor': '#e8e6dc', 'edgeLabelBackground': '#141413'}}}%%
graph LR
    S["Specify<br/>WHAT / WHY"] --> P["Plan<br/>HOW"]
    P --> T["Tasks<br/>découpage"]
    T --> I["Implement<br/>exécution"]

    style S fill:#d97757,stroke:#d97757,color:#141413
    style P fill:#1e1e1c,stroke:#d97757,color:#e8e6dc
    style T fill:#1e1e1c,stroke:#d97757,color:#e8e6dc
    style I fill:#1e1e1c,stroke:#b0aea5,color:#b0aea5
